### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#2252]
I clone the repo into my project
```
git clone git://github.com/uikit/uikit.git
```

Next go to uikit folder, and run:
```
npm install
```
Effect:
```
npm WARN uikit@3.0.0-beta.3 No repository field.
npm WARN uikit@3.0.0-beta.3 No license field.
```

Next 
```
npm run compile
```
is failed, the npm-debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodeJS\\node.exe',
1 verbose cli   'C:\\Users\\PixelT\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle uikit@3.0.0-beta.3~precompile: uikit@3.0.0-beta.3
6 silly lifecycle uikit@3.0.0-beta.3~precompile: no script for precompile, continuing
7 info lifecycle uikit@3.0.0-beta.3~compile: uikit@3.0.0-beta.3
8 verbose lifecycle uikit@3.0.0-beta.3~compile: unsafe-perm in lifecycle true
9 verbose lifecycle uikit@3.0.0-beta.3~compile: PATH: C:\Users\PixelT\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\PROJEKTY\pixeltown2\wp-content\themes\pixeltheme\uikit\node_modules\.bin;C:\Program Files\ImageMagick-7.0.3-Q16;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\nodeJS\;C:\Program Files\Git\cmdC:\ProgramData\ComposerSetup\bin;C:\wamp64\bin\php\php7.0.10;C:\Program Files\Git\cmd\;C:\Ruby22-x64\bin;C:\Users\PixelT\AppData\Local\Microsoft\WindowsApps;C:\Users\PixelT\AppData\Roaming\npm;C:\Users\PixelT\AppData\Local\atom\bin;C:\Users\PixelT\AppData\Roaming\Composer\vendor\bin;C:\wamp64\bin\php
10 verbose lifecycle uikit@3.0.0-beta.3~compile: CWD: D:\PROJEKTY\pixeltown2\wp-content\themes\pixeltheme\uikit
11 silly lifecycle uikit@3.0.0-beta.3~compile: Args: [ '/d /s /c', 'npm run compile-less && npm run compile-js' ]
12 silly lifecycle uikit@3.0.0-beta.3~compile: Returned: code: 1  signal: null
13 info lifecycle uikit@3.0.0-beta.3~compile: Failed to exec compile script
14 verbose stack Error: uikit@3.0.0-beta.3 compile: `npm run compile-less && npm run compile-js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\PixelT\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\PixelT\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid uikit@3.0.0-beta.3
16 verbose cwd D:\PROJEKTY\pixeltown2\wp-content\themes\pixeltheme\uikit
17 error Windows_NT 10.0.14393
18 error argv "E:\\nodeJS\\node.exe" "C:\\Users\\PixelT\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
19 error node v6.9.4
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error uikit@3.0.0-beta.3 compile: `npm run compile-less && npm run compile-js`
22 error Exit status 1
23 error Failed at the uikit@3.0.0-beta.3 compile script 'npm run compile-less && npm run compile-js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the uikit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run compile-less && npm run compile-js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs uikit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls uikit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Tell the author that this fails on your system:
```
npm ERR!     lessc --relative-urls --rootpath=../../src/less/ src/less/uikit.less > dist/css/uikit-core.css
npm ERR!     mkdir dist & mkdir dist/css & npm run images && npm run compile-less-core && npm run compile-less-theme && node build/less && node build/css-minify
```

**UPDATE**
npm run compile - error
npm run compile-less - error
npm run compile-js - work OK

**Comment by janschoenherr** [comment]
Please try Window's Powershell or the new bash: http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by janschoenherr** [comment]
I will close the issue for now. The build process has changed quite a bit. Please reopen if the issue persists.
