### ISSUE TITLE
sticky: Cannot read property 'getWidthFrom' of undefined     at o.computeWrapper

### ISSUE THREAD

**Issue by badpenguin** [uikit/uikit#2275]
Any idea how to fix this error with 2.27.2 ?
```
sticky.min.js:2 Uncaught TypeError: Cannot read property 'getWidthFrom' of undefined
    at o.computeWrapper (assets/uikit-2.27.2/js/components/sticky.min.js:2:4886)
    at o.init (assets/uikit-2.27.2/js/components/sticky.min.js:2:2301)
    at new o (assets/uikit-2.27.2/js/uikit.min.js:2:6776)
    at Object.(anonymous function) [as sticky] (assets/uikit-2.27.2/js/uikit.min.js:2:8068)
    at HTMLElement.<anonymous> (assets/uikit-2.27.2/js/components/sticky.min.js:2:2100)
    at Function.each (assets/jquery/jquery-2.2.3.min.js:2:2861)
    at n.fn.init.each (assets/jquery/jquery-2.2.3.min.js:2:845)
    at assets/uikit-2.27.2/js/components/sticky.min.js:2:2048
computeWrapper @ sticky.min.js:2
init @ sticky.min.js:2
o @ uikit.min.js:2
(anonymous function) @ uikit.min.js:2
(anonymous) @ sticky.min.js:2
each @ jquery-2.2.3.min.js:2
each @ jquery-2.2.3.min.js:2
(anonymous) @ sticky.min.js:2
setTimeout (async)
(anonymous) @ sticky.min.js:2
(anonymous) @ uikit.min.js:2
n.init @ uikit.min.js:2
(anonymous) @ uikit.min.js:2
dispatch @ jquery-2.2.3.min.js:3
r.handle @ jquery-2.2.3.min.js:3
trigger @ jquery-2.2.3.min.js:4
(anonymous) @ jquery-2.2.3.min.js:4
each @ jquery-2.2.3.min.js:2
each @ jquery-2.2.3.min.js:2
trigger @ jquery-2.2.3.min.js:4
n.trigger @ uikit.min.js:2
t @ uikit.min.js:2
```

**Comment by svjansen** [comment]
I need to see how you try to use the sticky component.

**Comment by badpenguin** [comment]
Well it works on any page but only onto the homepage it raise that error.
```
<body class="homepage" >
<div id="page">
<header class="my-sticky"  data-uk-sticky="{media:760,top:-300,animation: 'uk-animation-slide-top'}" >
<nav id="menubar-primary" class="uk-navbar" role="navigation" >...</nav>
</header>
<div class="uk-slidenav-position" data-uk-slideshow="{autoplay:true, kenburns:true, animation: 'fade'}" >```

**Comment by lanc3lot** [comment]
Was this solved somehow? Same problem too here

**Comment by kidmeke** [comment]
I had the same issue and created pull request #4027 to fix it (computeWrapper() has a code path that assumes this.sticky is defined, but this.sticky is not set up until after call to computeWrapper()...)
