### ISSUE TITLE
UIkit 3 - UIkit.component is not a function

### ISSUE THREAD

**Issue by cj** [uikit/uikit#2345]
`TypeError: UIkit.component is not a function. (In 'UIkit.component', 'UIkit.component' is undefined)`

In my webpack config I have:

```
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      "window.jQuery": 'jquery',
      "UIkit": 'uikit',
      "Vue": 'vue'
    })
```

In my app I'm doing `import 'uikit'`

**Comment by hoangcuongvn** [comment]
I have the same problem when trying using uikit with webpack.

**Comment by mjbates7** [comment]
I also have this issue unfortunately like when I want to use the notification component etc. Hope this gets sorted!

**Comment by Nayir** [comment]
Same for me. Someone find a trick for that ?

**Comment by hoangcuongvn** [comment]
@Nayir I just found a workaround. We can use it as an external library in webpack.
https://github.com/uikit/uikit-site/blob/develop/webpack.config.js#L2

**Comment by janschoenherr** [comment]
Can you give the new Beta 11 a try?

**Comment by blagodus** [comment]
@janschoenherr  this error is gone in Beta 11(for me). 

I'm using UIkit with mithril.js and now i get this error:
```
Uncaught TypeError: UIkit.update is not a function
    at Nav._toggle (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:1948:19)
    at Nav.eval [as _toggle] (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:579:31)
    at Nav._toggleImmediate (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:1952:18)
    at eval (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:579:31)
    at Nav._toggleElement (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:1929:14)
    at Nav.eval [as _toggleElement] (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:579:31)
    at eval (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:1891:96)
    at Array.map (native)
    at Nav.toggleNow (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:1891:62)
    at Nav.eval [as toggleNow] (eval at <anonymous> (http://localhost:4444/assets/js/app.js:111:1), <anonymous>:579:31)
```

If i try to `console.log(UIkit.update())` from my script i get same error..
For `console.log(UIkit)` i get : 
```
function plugin(UIkit) {

    if (plugin.installed) {
        return;
    }

    var ref = UIkit.util;
    var $ = ref.$;
    var ajax = ref.ajax;
    var on = ref.on;

    UIkit.component('upload', {…
```

**Comment by TheInternerd12** [comment]
@blagodus same error for me

**Comment by aarongerig** [comment]
I can confirm @blagodus issue with UIkit 3 and Webpack. Right now I'm using version 3.0.0-beta.6 and it works. But if I update any version higher than beta.6 I run into the error
`UIkit.update is not a function`

**Comment by filly82** [comment]
Updated to Beta13 today, still got the same error

Uncaught TypeError: UIkit.update is not a function
    at Accordion._toggle (js/bundle.js:13692:19)
    at Accordion._toggle (js/bundle.js:11870:31)
    at Accordion._toggleImmediate (js/bundle.js:13696:18)
    at js/bundle.js:11870:31
    at Accordion._toggleElement (js/bundle.js:13669:14)
    at Accordion._toggleElement (js/bundle.js:11870:31)
    at js/bundle.js:13628:98
    at Array.map (native)
    at Accordion.toggleNow (js/bundle.js:13628:64)
    at Accordion.toggleNow (js/bundle.js:11870:31)

**Comment by janschoenherr** [comment]
This has been fixed with the latest Beta.
