### ISSUE TITLE
Compatibility issues with requirejs

### ISSUE THREAD

**Issue by deviprsd21** [uikit/uikit#2376]
When using uikit with aurelia, with a project set up with aurelia-cl, uikit isn't getting loaded properly. My aurelia.json dependency is something like this 

```json
"dependencies": [
    "jquery",
    "uikit"
]
```
When loading the aurelia website this is the error thrown in the console
```
Uncaught Error: Mismatched anonymous define() module: function ($) { 'use strict';

var $__default = 'default' in $ ? $['default'] : $;
```
![2017-02-09](https://cloud.githubusercontent.com/assets/3809354/22774055/5319f6f4-eecb-11e6-8bb3-362a85110fcc.png)

**Comment by janschoenherr** [comment]
Is this still happening with Beta 11?

**Comment by edson-gaspar** [comment]
+1. It's still happening on CDN repository with Beta 11.

**Comment by deviprsd21** [comment]
Yup still happening in bet 11.

**Comment by chay22** [comment]
+1
Is there any recommendation of version 3 beside beta 11 which is currently working?

**Comment by chay22** [comment]
Seems like https://github.com/rollup/rollup causes this

```
Uncaught TypeError: UIkit.update is not a function
    at Modal._toggle (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:12249:19)
    at Modal._toggle (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:10880:31)
    at Modal._toggleImmediate (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:12253:18)
    at http://localhost:8000/js/base.c4e53bff5aa049c535df.js:10880:31
    at Modal._toggleElement (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:12230:14)
    at Modal._toggleElement (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:10880:31)
    at http://localhost:8000/js/base.c4e53bff5aa049c535df.js:12192:96
    at Array.map (native)
    at Modal.toggleNow (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:12192:62)
    at Modal.toggleNow (http://localhost:8000/js/base.c4e53bff5aa049c535df.js:10880:62)
```

Looked in to the dist file
```javascript
_toggle: function _toggle(el, toggled) {

    el = $__default(el);

    if (this.cls) {
        el.toggleClass(this.cls, ~this.cls.indexOf(' ') ? undefined : toggled);
    } else {
        el.attr('hidden', !toggled);
    }

    el.find('[autofocus]:visible').focus();

    this.updateAria(el);
    UIkit.update(null, el);
},
```
`UIkit` is not defined since it was renamed as 

```javascript
var UIkit$1 = function (options) {
    this._init(options);
};

UIkit$1.util = util;
UIkit$1.data = '__uikit__';
UIkit$1.prefix = 'uk-';
UIkit$1.options = {};
UIkit$1.instances = {};
UIkit$1.elements = [];
```

**Comment by janschoenherr** [comment]
Fixed in latest Beta 14.
