### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by gabyferman** [uikit/uikit#2679]
### UIkit version

3.0.0-beta.22

### What is actually happening?

I'm trying to compile my uikit install with npm and I keep getting this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\gaby1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@4.6.1
3 info using node@v6.10.3
4 verbose stack Error: missing script: compile
4 verbose stack     at run (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:189:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\gaby1\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd C:\xampp\htdocs\erus\wp-content\themes\sway-parent\node_modules\uikit
6 verbose Windows_NT 10.0.14393
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gaby1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
8 verbose node v6.10.3
9 verbose npm  v4.6.1
10 error missing script: compile
11 verbose exit [ 1, true ]
```

Is this an error in the uikit source file?

**Comment by aarongerig** [comment]
Make sure you run this command inside the `uikit` folder. The error you see is saying that the command `compile` wasn't found, which means you are missing the `package.json` file of uikit.

Always be sure to run the following cmds:

1. (inside your project root) `npm install --save uikit`
2. `cd node_modules/uikit`
3. `npm install`
4. change the files inside `src` folder
5. `npm run compile`
6. link the files inside `dist` folder

**Comment by florianletsch** [comment]
Thanks aaron for explaining, I also think it was just run from the wrong directory. For further details on how to build, please refer to https://getuikit.com/docs/installation and https://getuikit.com/docs/less
