### ISSUE TITLE
Notification throws an error

### ISSUE THREAD

**Issue by nZac** [uikit/uikit#2681]
### UIkit version
3.0.0-beta.23 (doesn't work as expected)
3.0.0-beta.22 (works as expected)

### Browser
Chrome 58.0.3029.110 (64-bit) Mac OS X

### Reproduction Link
https://gist.github.com/nZac/b1de8ffe1e1b959eb6902816d8cb0f28

### Steps to reproduce
Run the code

### What is Expected?
Load the page

### What is actually happening?
An exception is thrown on the first loop, however later iterations allow the notification to display.

```
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at Notification.UIkit._getProps (http://localhost:5000/static/js/bundle.js:12413:25)
    at Notification.UIkit._initProps (http://localhost:5000/static/js/bundle.js:12348:43)
    at Notification.UIkit.$mount (http://localhost:5000/static/js/bundle.js:12574:14)
    at Notification.created (http://localhost:5000/static/js/bundle.js:16966:18)
    at http://localhost:5000/static/js/bundle.js:12131:66
    at Array.forEach (native)
    at Notification.UIkit._callHook (http://localhost:5000/static/js/bundle.js:12131:22)
    at Notification.UIkit._init (http://localhost:5000/static/js/bundle.js:12275:14)
    at new Notification (eval at createClass (http://localhost:5000/static/js/bundle.js:12089:16), <anonymous>:2:47)
    at Function.UIkit.(anonymous function) [as notification] (http://localhost:5000/static/js/bundle.js:12667:24)
```

**Comment by janschoenherr** [comment]
Thanks, resolved with 31b1c942ce097a2d917531b121eac1aa2a2d322c
