### ISSUE TITLE
Error when running npm run watch

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#2836]
**Environment**  

Windows 7 Enterprise
UIkit:  3.0.0 beta 28

**Steps to install UIkit were**

1) Create folder on desktop `MyApp 2.0`

2) Navigate to newly created folder

3)  Run

        D:\Users\Me\Desktop\MyApp 2.0>npm install --prefix ./ uikit

4)  This creates the folders `etc` and `node_modules` in the folder `MyApp 2.0`

5)  `node_modules` contains a folder called `uikit`

6)  Cut all contents of `uikit` folder and paste in the root app folder, ie the `MyApp 2.0`.  

7)  Delete the now empty `etc` and `node_modules` folders in the root app directory.  

8)  Run the following to install UIkit dependencies defined in `package.json`

         D:\Users\Me\Desktop\MyApp 2.0>npm install

This produces warnings:

        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
        okidar\node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
        1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
        )

9)  Create a `custom` folder in the application root directory with the contents:

- icons (for custom icons)
- my-theme.less (my theme)

10)  Add my `index.html` file to the application root directory. 

11)  Add `jquery-3.2.1.min.js` to `/dist/js`

12)  Run

         D:\Users\Me\Desktop\MyApp 2.0>npm run compile

13)  Run the following to "watch files and compile automatically everytime a file changes"  

         D:\Users\Me\Desktop\MyApp 2.0>npm run watch

**Error**

    > npm-watch

	No task specified. Will go through all possible tasks
	[compile-js] [nodemon] 1.11.0
	[compile-js] events.js:160
	      throw er; // Unhandled 'error' event
	      ^

	Error: spawn cmd ENOENT
	    at exports._errnoException (util.js:1018:11)
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	    at onErrorNT (internal/child_process.js:367:16)
	    at _combinedTickCallback (internal/process/next_tick.js:80:11)
	    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by oshihirii** [comment]
Per [this post](https://stackoverflow.com/a/39872252/1063287), I deleted the `node_modules` folder and then ran:

    npm cache clean
    npm install

And I get the same error when running `npm run watch`:

    > npm-watch

	No task specified. Will go through all possible tasks
	[compile-js] [nodemon] 1.11.0
	[compile-js] events.js:160
	      throw er; // Unhandled 'error' event
	      ^

	Error: spawn cmd ENOENT
	    at exports._errnoException (util.js:1018:11)
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	    at onErrorNT (internal/child_process.js:367:16)
	    at _combinedTickCallback (internal/process/next_tick.js:80:11)
	    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by florianletsch** [comment]
This feels like a Windows related issue to me (which I can't support personally).

Maybe someone else can?

Maybe just try adding the right path to your PATH variable? A quick google search turned up several of these suggestions: https://stackoverflow.com/questions/31398380/fatal-error-spawn-cmd-enoent-grunt-serve

**Comment by oshihirii** [comment]
Thanks for suggestion, I ran `npm cache clean`, and added path as suggested in that post and initially got an error:

    No task specified. Will go through all possible tasks
    [compile-less] [nodemon] 1.11.0
    [compile-less] [nodemon] watching: **/*.less
    [compile-less] [nodemon] starting `npm.cmd run -s compile-less`
    [compile-less] events.js:160
          throw er; // Unhandled 'error' event
          ^

    Error: spawn cmd ENOENT
        at exports._errnoException (util.js:1018:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
        at onErrorNT (internal/child_process.js:367:16)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)
    [compile-js] [nodemon] 1.11.0
    [compile-js] [nodemon] watching: src/js/**/*.js
    [compile-js] [nodemon] starting `npm.cmd run -s compile-js`
    [compile-js] events.js:160
          throw er; // Unhandled 'error' event
          ^

    Error: spawn cmd ENOENT
        at exports._errnoException (util.js:1018:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
        at onErrorNT (internal/child_process.js:367:16)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)

However, then I closed and opened terminal a couple of times and now `npm run watch` is working! Hallelujah!

**Comment by harishrathor** [comment]
Thanks @oshihirii . It also worked for me.
