### ISSUE TITLE
$-moz-document url-prefix() in utility.scss should be an @ symbol

### ISSUE THREAD

**Issue by mohamedhamad** [uikit/uikit#3379]
looks like there is a typo in the utility.scss file which is blocking webpack from compiling
in line 355, it should be @-moz-document url-prefix() and not $-moz-document url-prefix() 

### UIkit version

3.0.0-rc.1

### Browser
All

### Steps to reproduce
compile with webpack

### What is Expected?
compiled code

### What is actually happening?
ERROR in ./assets/scss/main.scss
Module build failed: ModuleBuildError: Module build failed:
$-moz-document url-prefix() {
^
      Expected ':' after $-moz-document in assignment statement
      in /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/uikit/src/scss/components/utility.scss (line 355, column 1)
    at runLoaders (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/node-sass/lib/index.js:294:32)
 @ ./assets/js/index.js 22:0-28

ERROR in ./assets/scss/main.scss
Module build failed: ModuleBuildError: Module build failed:
$-moz-document url-prefix() {
^
      Expected ':' after $-moz-document in assignment statement
      in /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/uikit/src/scss/components/utility.scss (line 355, column 1)
    at runLoaders (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/mohammedhamad/Sites/pwl/wp-content/themes/pwl-theme/node_modules/node-sass/lib/index.js:294:32)
 @ ./assets/scss/main.scss
 @ ./assets/js/index.js

**Comment by aarongerig** [comment]
Thanks for reporting, will be fixed with the next release: https://github.com/uikit/uikit/commit/f25ed57afae5cf1c844f9fda6c33137b8b5f26a6
