### ISSUE TITLE
Error: Cannot find module 'fs-extra' on npm run compile

### ISSUE THREAD

**Issue by oshihirii** [uikit/uikit#3405]
### UIkit version
3.0.0-rc.4

### Steps to reproduce

    $ npm run compile

### What is Expected?

I expect build to complete and output required js and css files.

### What is actually happening?

> uikit@3.0.0-rc.4 compile C:\Users\Me\Documents\my_repo\node_modules\uikit
> yarn compile-less && yarn compile-js
> 
> yarn run v1.7.0
> warning ..\..\package.json: License should be a valid SPDX license expression
> $ yarn icons && node build/less
> warning ..\..\package.json: License should be a valid SPDX license expression
> $ node build/icons
> internal/modules/cjs/loader.js:573
>     throw err;
>     ^
> 
> Error: Cannot find module 'fs-extra'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (C:\Users\Me\Documents\my_repo\node_modules\uikit\build\util.js:1:74)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> error Command failed with exit code 1.

**Anomalies:**

Earlier today I was prompted to update Gitbash, so I don't know if that has effected something?

**Comment by oshihirii** [comment]
Hmm, had to run `npm install yarn` _and_ `npm install` after updating `uikit`.
