### ISSUE TITLE
Failed to execute 'getTotalLength' when hiding SVG with stroke animation

### ISSUE THREAD

**Issue by ilikerobots** [uikit/uikit#4132]
I am using parallax to do stroke animation on a SVG.  However, I want to the SVG on < large screens. I can't find any way to hide it from the page without causing the following JS error, which then prevents other Uikit JS from executing.

Even when providing a media:@l option to the parallax, the error still occurs.

### UIkit Version
3.3.2

### Actual Behavior
Javascript error: 
```
uikit.min.js:3 Uncaught DOMException: Failed to execute 'getTotalLength' on 'SVGGeometryElement': This element is non-rendered element.
    at https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:56203
    at Array.map (<anonymous>)
    at Pn (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:56160)
    at https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:111756
    at Array.reduce (<anonymous>)
    at e.props (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:110913)
    at e.get [as props] (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:28197)
    at e.getCss (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:113283)
    at e.reset (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:113204)
    at e.write (https://cdn.jsdelivr.net/npm/uikit@3.3.2/dist/js/uikit.min.js:3:114969)
```

### Expected Behavior

No error; or at least a way to prevent the situation that causes the error.

*What should have happened?*

### Reproduction Link
Minimal example here: http://www.starheightmedia.com/uikit/
(sorry not codepen, i could't find an svg with CORS headers suitable)

Note all works fine at @l breakpoint.  But if the screen is shrunk to < @l, and the page is reloaded, the JS error above occurs.

### Steps to Reproduce the Problem

1. Build a simple SVG stroke parallax per the examples
2. Have the parallax element start hidden on the page.  
3. Load the page in browser.

**Comment by ilikerobots** [comment]
thanks @sahilNR !
 
for anyone else running into this before this fix can be released, I've worked around it by setting the container holding the svg to absolute positioning with zero height/width instead of visibility, effectively hiding it while still allowing it to be rendered and avoiding the error.
