### ISSUE TITLE
Override of default icons not possible

### ISSUE THREAD

**Issue by sOmiloef** [uikit/uikit#5078]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.21.13

### Actual Behavior

It's not possible to override the default icons with an custom icon. I think that the order in which the icons are processed is wrong. So the default icons will override the custom icons.

### Expected Behavior

I would expect, that i can override an default icon with on icon that's located in the folder for custom icons.

### Reproduction Link

--- 

### Steps to Reproduce the Problem

1. Put an icon with the name "plus-circle" in the `/custom/icons` folder.
2. Run pnpm compile
3. The icon is still the original icon and not that from the `custom`-folder

**Comment by voyou-yvchesteing** [comment]
I’m encountering the same issue with version 3.21.16. When I follow the instructions for creating custom icons (whether within a theme or not), it no longer works.

When I use `/custom/icons`, the new JavaScript file doesn’t include the custom icons.
When I use the theme option `/custom/theme/icons`, I get an error while running `pnpm` :

```
> uikit@3.21.16 icons C:\Users\USERNAME\Documents\Sites\uikit-3.21.16
> node build/icons

file:///C:/Users/USERNAME/Documents/Sites/uikit-3.21.16/build/icons.js:28
    const [, name] = folder.match(new RegExp(match, 'i'));
                     ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at compileIcons (file:///C:/Users/USERNAME/Documents/Sites/uikit-3.21.16/build/icons.js:28:22)
    at Array.map (<anonymous>)
    at file:///C:/Users/USERNAME/Documents/Sites/uikit-3.21.16/build/icons.js:25:38

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
I still have a project running version 3.15.1, and I don’t encounter any issues there.
